version: '2.2'

services:
  postgres:
    container_name: local_postgres
    image: postgres:9.6
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
      PGDATA: /data/postgres
    command: -c 'max_connections=1024'  
    volumes:
       - postgres:/data/postgres
    ports:
      - "5466:5432"
    networks:
      - postgres
    restart: unless-stopped
    privileged: true
    cap_drop:
      - ALL
    cpu_count: 2
    mem_limit: 512m

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
